server.port: 8080

spring:
  application.name: gateway
  main.web-application-type: reactive

app.eureka-server: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

spring.cloud.gateway.routes:

  - id: product-composite
    uri: lb://product-composite
    predicates:
      - Path=/products-composite/**

  - id: product-composite-swagger-ui
    uri: lb://product-composite
    predicates:
      - Path=/openapi/**

---
spring.config.activate.on-profile: docker

app.eureka-server: eureka