spring.application.name: products

server:
  port: 7001

spring.data.mongodb:
  host: localhost
  port: 27017
  database: product-db

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings:
    messageProcessor-in-0:
      destination: products
      group: productsGroup

      consumer:
        partitioned: true
        instance-index: 0

    messageProcessor-in-0.consumer:
      maxAttempts: 3
      backOffInitialInterval: 500
      backOffMaxInterval: 1000
      backOffMultiplier: 2.0

  rabbit.bindings.messageProcessor-in-0.consumer:
    autoBindDlq: true
    republishToDlq: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5 #Indicates how long initially (in seconds) to replicate instance info to the eureka server
    registryFetchIntervalSeconds: 5 #Indicates how often(in seconds) to fetch the registry information from the eureka server.
  instance:
    leaseRenewalIntervalInSeconds: 5 #Indicates how often (in seconds) the eureka client needs to send heartbeats to eureka server to indicate that it is still alive.
    leaseExpirationDurationInSeconds: 5 #Indicates the time in seconds that the eureka server waits since it received the last heartbeat before it can remove this instance

---

spring.config.activate.on-profile: docker

server.port: 8080

spring.data.mongodb.host: mongodb

eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/